# Generated by Django 3.0.3 on 2020-03-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='CityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='imagesearch.City'),
        ),
        migrations.AlterField(
            model_name='message',
            name='From',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='message_from', to='imagesearch.Person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='To',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='message_to', to='imagesearch.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='AddressID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagesearch.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='TemplatePhoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagesearch.Photo'),
        ),
    ]
