# Generated by Django 3.0.3 on 2020-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesearch', '0002_auto_20200320_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
